/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/girls/': RouteRecordInfo<'/girls/', '/girls', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/music/': RouteRecordInfo<'/music/', '/music', Record<never, never>, Record<never, never>>,
    '/oldposts/planning': RouteRecordInfo<'/oldposts/planning', '/oldposts/planning', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/复变函数在工程领域应用概述': RouteRecordInfo<'/posts/复变函数在工程领域应用概述', '/posts/复变函数在工程领域应用概述', Record<never, never>, Record<never, never>>,
    '/posts/高级语言程序设计-Python实验报告三': RouteRecordInfo<'/posts/高级语言程序设计-Python实验报告三', '/posts/高级语言程序设计-Python实验报告三', Record<never, never>, Record<never, never>>,
    '/posts/高级语言程序设计Python实验报告二': RouteRecordInfo<'/posts/高级语言程序设计Python实验报告二', '/posts/高级语言程序设计Python实验报告二', Record<never, never>, Record<never, never>>,
    '/posts/高级语言程序设计Python实验报告一': RouteRecordInfo<'/posts/高级语言程序设计Python实验报告一', '/posts/高级语言程序设计Python实验报告一', Record<never, never>, Record<never, never>>,
    '/posts/基于DGSC算法的校园网用户行为分析': RouteRecordInfo<'/posts/基于DGSC算法的校园网用户行为分析', '/posts/基于DGSC算法的校园网用户行为分析', Record<never, never>, Record<never, never>>,
    '/posts/领导力与沟通个人作业': RouteRecordInfo<'/posts/领导力与沟通个人作业', '/posts/领导力与沟通个人作业', Record<never, never>, Record<never, never>>,
    '/posts/数学建模-数值逼近': RouteRecordInfo<'/posts/数学建模-数值逼近', '/posts/数学建模-数值逼近', Record<never, never>, Record<never, never>>,
    '/posts/数学建模-线性规划': RouteRecordInfo<'/posts/数学建模-线性规划', '/posts/数学建模-线性规划', Record<never, never>, Record<never, never>>,
    '/posts/a-free-domain-in-freenom': RouteRecordInfo<'/posts/a-free-domain-in-freenom', '/posts/a-free-domain-in-freenom', Record<never, never>, Record<never, never>>,
    '/posts/C-Class1': RouteRecordInfo<'/posts/C-Class1', '/posts/C-Class1', Record<never, never>, Record<never, never>>,
    '/posts/C-Class2': RouteRecordInfo<'/posts/C-Class2', '/posts/C-Class2', Record<never, never>, Record<never, never>>,
    '/posts/C-Class3': RouteRecordInfo<'/posts/C-Class3', '/posts/C-Class3', Record<never, never>, Record<never, never>>,
    '/posts/dismount-battery': RouteRecordInfo<'/posts/dismount-battery', '/posts/dismount-battery', Record<never, never>, Record<never, never>>,
    '/posts/informal-piano-room': RouteRecordInfo<'/posts/informal-piano-room', '/posts/informal-piano-room', Record<never, never>, Record<never, never>>,
    '/posts/myfuture-mylife-mycollege': RouteRecordInfo<'/posts/myfuture-mylife-mycollege', '/posts/myfuture-mylife-mycollege', Record<never, never>, Record<never, never>>,
    '/posts/PE-guide': RouteRecordInfo<'/posts/PE-guide', '/posts/PE-guide', Record<never, never>, Record<never, never>>,
    '/posts/purchase-guide-2023': RouteRecordInfo<'/posts/purchase-guide-2023', '/posts/purchase-guide-2023', Record<never, never>, Record<never, never>>,
    '/posts/R': RouteRecordInfo<'/posts/R', '/posts/R', Record<never, never>, Record<never, never>>,
    '/posts/the-art-of-homework': RouteRecordInfo<'/posts/the-art-of-homework', '/posts/the-art-of-homework', Record<never, never>, Record<never, never>>,
    '/posts/windows-restart-explorer': RouteRecordInfo<'/posts/windows-restart-explorer', '/posts/windows-restart-explorer', Record<never, never>, Record<never, never>>,
    '/projects/': RouteRecordInfo<'/projects/', '/projects', Record<never, never>, Record<never, never>>,
    '/slides/': RouteRecordInfo<'/slides/', '/slides', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
